name: vendy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vendy_banner.jpg
    - assets/beverages_icon.png
    - assets/cold_meals_icon.png
    - assets/snacks_icon.png
    - assets/hot_meals_icon.png
    - assets/vending_machine.png
    - assets/history_outlined.png
    - assets/history.png
    - assets/home_outlined.png
    - assets/home.png
    - assets/profile_outlined.png
    - assets/profile.png
    - assets/settings_outlined.png
    - assets/settings.png
    - assets/menu_item.jpg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
